# Project
group=bl4ckscor3.mod.easterrabbits
version=1.1
minecraft_version=26.1.2
minecraft_min_version=26.1
java_version=25
license=MIT
mod_id=easterrabbits
mod_name=EasterRabbits
description=Makes rabbits lay eggs every now and then.
mod_author=bl4ckscor3
source_link=https://github.com/bl4ckscor3/GEasterRabbits
cf_link=https://www.curseforge.com/minecraft/mc-mods/easter-rabbits

# Common
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1
mdg_version=2.0.141
run_dir=../runs

# NeoForge
neoforge_version=26.1.2.27-beta
neoforge_min_version=26.1

# Fabric
loom_version=1.15-SNAPSHOT
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.8

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
