modLoader="javafml"
loaderVersion="[37,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/EasterRabbits/blob/1.17/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/EasterRabbits/issues"

[[mods]]
	modId="easterrabbits"
	version="${file.jarVersion}"
	displayName="Easter Rabbits"
	description='''Makes rabbits lay eggs every now and then.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/easter-rabbits"
	authors="bl4ckscor3"

[[dependencies.easterrabbits]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easterrabbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"