modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/EasterRabbits/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/easter-rabbits"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="easterrabbits" #mandatory
version="v1.0.1" #mandatory
displayName="Easter Rabbits" #mandatory
description='''Makes rabbits lay eggs every now and then.''' #mandatory

[[dependencies.easterrabbits]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easterrabbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"