modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/EasterRabbits/issues"
displayURL="http://minecraft.curseforge.com/projects/easter-rabbits"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="easterrabbits" #mandatory
version="v1.0" #mandatory
displayName="Easter Rabbits" #mandatory
description='''Makes rabbits lay eggs every now and then.''' #mandatory

[[dependencies.easterrabbits]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easterrabbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"