license="MIT https://github.com/bl4ckscor3/EasterRabbits/blob/26.1/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/EasterRabbits/issues"

[[mods]]
	modId="easterrabbits"
	version="${file.jarVersion}"
	displayName="Easter Rabbits"
	description='''Makes rabbits lay eggs every now and then.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/easter-rabbits"
	authors="bl4ckscor3"

[[dependencies.easterrabbits]]
    modId="neoforge"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.easterrabbits]]
    modId="minecraft"
    type="required"
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"